services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    networks:
      uninuvola:
        ipv4_address: ${LDAP_IP}
    environment:
      LDAP_LOG_LEVEL: "0"
      LDAP_ORGANISATION: ${PROJECT}
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: ${READONLY_USER_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${READONLY_USER_PASSWORD}
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      # LDAP_TLS: "true"
      # LDAP_TLS_CRT_FILENAME: "ldap.crt"
      # LDAP_TLS_KEY_FILENAME: "ldap.key"
      # LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      # LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      # LDAP_TLS_ENFORCE: "false"
      # LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      # LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/

    # ports:
    #   - "389:389"
    #   - "636:636"

    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: ${DOMAIN}
    hostname: "ldap-server"

  phpldapadmin:
    networks:
      uninuvola:
        ipv4_address: ${LDAPADMIN_IP}
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    #ports:
    #  - 8081:80
    depends_on:
      - openldap

networks:
  uninuvola:
    external: true
