[tool.poetry]
name = "openldap"
version = "0.1.0"
description = ""
authors = ["Nicolò Vescera <nicolo.vescera@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ldap3 = "^2.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
